### PR TITLE
update hashbrown

### PR DESCRIPTION
**Pull request by xMAC94x**

### CODE REVIEW

**Review by zakarumych — APPROVED** [review]
Sounds goods. Thanks!

**Comment by bjorn3** [comment]
@zakarumych can you please publish a new version? The latest version on crates.io is still 0.2.1.

**Comment by zakarumych** [comment]
Done

**Comment by bjorn3** [comment]
Thanks!

**Comment by a1phyr** [comment]
@zakarumych could you release version `0.2.2` with this patch please ? `gpu-descriptor` is the last crate of my dependency tree that depends on `hashbrown` `0.9`.

**Pull request merged**
