### PR TITLE
build: remove unnecessary `allocator-api2` dep.

### PR DESCRIPTION
**Pull request by ErichDonGubler**

### CODE REVIEW

**Comment by zakarumych** [comment]
What is negative effect of the dependency?

**Comment by ErichDonGubler** [comment]
To directly answer your question: The presence of an unused dependency can be particularly burdensome in situations like Firefox's (i.e., in [this patch stack](https://phabricator.services.mozilla.com/D208390) where I'm revendoring WGPU), where trust for third-party dependencies are established by detailed review of each dependency's source. Each dependency in the tree is required to undergo significant scrutiny for the purposes of security, _for each version_. For what I hope are obvious reasons, when a dependency isn't actually used, our preference is to simply avoid the dependency altogether.

Taking a step back, your question surprises me. What user would _want_ an unused-but-still-built dependency in their project? By default, I wouldn't expect a project using `gpu-descriptor` to ever be interested in the `allocator-api2` crate, because its usage of `hashbrown` is not directly exposed in `gpu-descriptor` (which, unless I'm missing something, would be necessary for specifying collection-specific allocators). If a user _does_ want this (i.e., via changing the `global` allocator in `allocator-api2`), they can still opt into it by selecting the appropriate features in their own direct dependency on `hashbrown`.

**Comment by ErichDonGubler** [comment]
CC @cwfitzgerald, who [was a stakeholder for the `hashbrown` upgrade](https://github.com/zakarumych/gpu-descriptor/pull/33#issuecomment-1624337601) that I work with on a regular basis. He's also a stakeholder for this, since WGPU doesn't need this, either.

**Comment by zakarumych** [comment]
It's not like a user would want unused but still built dependency, but many users are not bothered enough to disable default ones.
My question was more like "how exactly it bothered you enough to go and submit a PR to disable it?"
And I thank you for thorough explanation.

**Pull request merged**
